name: weather_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  weather_api:
    path: ../weather_api
  

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0