name: weather_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0
  weather_api:
    path: ../weather_api
  dio: ^4.0.4

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  very_good_analysis: ^2.4.0